### ISSUE TITLE
GSOC22 RFE: k6 + prometheus + quality evaluation

### ISSUE THREAD

**Issue by agardnerIT** [keptn-sandbox/k6-service#18]
@jainammm now has a working k6 + prometheus extension container which runs k6 then pushes metrics to Prom.

The ask for this issue is to extend that Keptn sequence and add a new task `evaluation` which will USE those outputted metrics in a Keptn quality gate.

The logical workflow is:

1) I run a load test with k6 and output metrics to Prometheus (completed)
2) I **use** those metrics by asking Keptn to evaluate a quality gate

Note: This workflow gives the benefit of both k6 thresholds (if they fail, step 1 will fail) but also encorporating other metrics in Prom. Meaning we can also evaluate metrics from sources other than k6. In other words, a wholistic quality evaluation.

## Demo Shipyard
```
apiVersion: "spec.keptn.sh/0.2.2"
kind: "Shipyard"
metadata:
  name: "argocd-demo-shipyard"
spec:
  stages:
    - name: "dev"
      sequences:
        - name: "mysequence"
          tasks:
            - name: "test"  # < k6 responds
            - name: "evaluation" # < lighthouse service + sli provider responds
```
