### ISSUE TITLE
Does Job Executor Service support multiple commands?

### ISSUE THREAD

**Issue by agardnerIT** [keptn-sandbox/k6-service#8]
@ppcano mentioned using the JES to first build a k6 binary with extensions using `xk6` then running that binary.

Does the Keptn Job Executor Service support running something like this:

```
xk6 build --with github.com/grafana/xk6-browser && k6 run ....
```

**Comment by jainammm** [comment]
No, it probably doesn't... tried to run a simple `echo` followed by `k6 run` command but it failed
it took the whole command as arguments to `echo`

### Config File
```yaml
apiVersion: v2
actions:
  - name: "Run k6"
    events:
      - name: "sh.keptn.event.test.triggered"
    tasks:
      - name: "Run k6 with Keptn"
        files:
          - /files
        image: "loadimpact/k6"
        # cmd: ["sh"]
        # args: ["/keptn/files/execution.sh", "&&", "ls" ]
        cmd: ["echo"]
        args: ["jainam-log", "&&", "k6", "run", "--duration", "30s", "--vus", "10", "/keptn/files/k6_test.js"]
```

### JES logs
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/30795272/176630510-414e1e28-cb9e-4f7b-a744-7253a12a6b5c.png">
